###############################################################################
#
# Makefile for a script (e.g. Python), project 6
#
# Students:
# Snir Sharristh, ID 305500001, snir.sharristh@mail.huji.ac.il
#
###############################################################################

all:
	chmod 700 Assembler

